### ISSUE TITLE
Save toolkit

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#1]
Logged in users would have the ability to save individual toolkits to reference later. These would appear in their user profile and would provide data on which toolkits are most popular. An indicator would appear on each toolkit detail page that shows how many users have saved the toolkit. This data would be used to sort toolkits on the filter page in order of relevance.

**Comment by fabio-bs** [comment]
I added the "Toolkits" tab on a user's profile page that lists saved toolkits and an indicator on each toolkit detail page that shows how many users have saved the toolkit. 
As specified in #13 this parameter is also used to calculate the relevance of the toolkit.
