### ISSUE TITLE
Toolkit submission form

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#12]
Currently, new toolkits are added by administrators via Airtable. This is also where tags are added and managed. Ultimately, these are used to filter toolkits in the Toolkit Navigator. A csv file is exported from Airtable and the data is migrated to WordPress using a plugin (@benguhin has documentation on this). 
Anyone may submit a toolkit using the forms feature in Airtable: https://airtable.com/shrCRoGDGqbzXb0k0
A "Submit new toolkit" feature on the WordPress site will collect these same data fields and, upon administrator review and approval, publish to the Toolkit Navigator as a new entry. The administrators will be able to add additional toolkit metadata/tags (Good For, Task Type, Adaptability, etc) before publishing. 
The Case Study intake form can be used as a pattern to start from: https://oecd-opsi.org/case-study-form/

**Comment by fabio-bs** [comment]
I created the page to [submit a new toolkit](https://staging.oecd-opsi.org/submit-new-toolkit/) based on the one on Airtable. To create the form I used a subset of the toolkit fields used in WordPress so, to get this result, I updated the labels and descriptions of some of these fields (for example the "User Toolkit" field label was renamed to "To whom would you recommend this toolkit?"). I then added the following fields: Your Email, Image (used to populate the featured image), Static Versions and Editable Versions to allow the user to provide the necessary information. Once the form is sent, a new toolkit with the status "Pending review" is saved.

**Comment by innovativeangela** [comment]
This looks great @fabio-bs Does the submission of a toolkit automatically generate a notification for admins? Is there an easy way to add human verification to this form? This will reduce spam. 
Just to clarify, the toolkit will not be visible unless an admin approves it, correct?

**Comment by fabio-bs** [comment]
Currently submitting a toolkit does not generate notifications, but I can make sure that an email notification is sent. Can you please provide me with the e-mail addresses to be notified? Alternatively, I can retrieve email addresses by taking them from registered users with a specific role (for example Editors). 
The form has a [honeypot field](https://solutionfactor.net/blog/2014/02/01/honeypot-technique-fast-easy-spam-prevention/) that should be sufficient to block spam. In case this is not enough we could insert a captcha. 
Finally, I confirm that the toolkit will not be visible until an administrator approves it.

**Comment by innovativeangela** [comment]
@fabio-bs Could you auto-generate emails to anyone with Editor role? Let's stick with honeypot field for the spam prevention.

**Comment by fabio-bs** [comment]
I implemented the notification using editor email addresses. 
Attached is an example of the message.
![toolkit-submission-notification](https://user-images.githubusercontent.com/9032846/48551876-0f78fc80-e8d7-11e8-8f22-d52d07c25703.JPG)

**Comment by innovativeangela** [comment]
@fabio-bs Could you please let me know where I can edit form fields and help text? I would like to make a few small edits to the toolkit intake form.

**Comment by fabio-bs** [comment]
@innovativeangela, as regards the modification of the help text it is sufficient to modify the content of the "Submit new toolkit" page. While editing the titles of the fields or their descriptions is an operation that can only be performed by users with the role of administrator. Furthermore, these changes affect both the form in the frontend and the creation/modification form of a toolkit in the backend. If you list the changes to be made I can do it myself

**Comment by innovativeangela** [comment]
@fabio-bs Can you please add help text below the Description field: "Please describe who this resource is for, what it includes, its purpose, and how it works. This helps others know whether it is right for them. These descriptions may be edited by OPSI before being published."

**Comment by fabio-bs** [comment]
@innovativeangela I made the change
