### ISSUE TITLE
Styling for "open source" toolkits

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#17]
Some toolkits are licensed to allow adaptation by others (Creative Commons licenses or OS licenses). This information is contained in the "Adaptability" field associated with each toolkit (None, Basic, Champion, Hero). I would like styling on the filter page and each toolkit detail page that designates the Hero toolkits. Perhaps the existing Badges feature used in the Case Study Platform could be used for this purpose.

**Comment by fabio-bs** [comment]
I added the badges to the [search results](https://staging.oecd-opsi.org/search-toolkits/?_sft_adaptability=hero) and to the [detail pages](https://staging.oecd-opsi.org/toolkits/demtools/) using (temporarily) images of the badges used for case studies. These images can be set directly by the Wordpress administration and in case a category does not have an image then the badge will not be shown.

**Comment by innovativeangela** [comment]
@fabio-bs can you change badge appearance so that badges only appear for "basic" "champion" and "hero" adaptability options? No badges should appear for "unknown" and "none" adaptability options.

**Comment by innovativeangela** [comment]
@fabio-bs Also, can the badge appear in the top right corner of each toolkit box on filter pages next to the toolkit title?

**Comment by innovativeangela** [comment]
@fabio-bs I viewed a few toolkits with badges. I noticed that the badge appeared in the filter view but not in the detail view in [this case](https://staging.oecd-opsi.org/toolkits/a-field-guide-to-ethnographic-experiential-futures/)

**Comment by innovativeangela** [comment]
![badge-hero](https://user-images.githubusercontent.com/22620143/48500110-5533b780-e83a-11e8-89ce-4f9c02cda292.png)
![badge-champion](https://user-images.githubusercontent.com/22620143/48500112-56fd7b00-e83a-11e8-9507-d0a128e6c2e3.png)
![badge-basic](https://user-images.githubusercontent.com/22620143/48500116-595fd500-e83a-11e8-9b95-64feca0424dd.png)
Please use these for basic, champion, and hero

**Comment by fabio-bs** [comment]
@innovativeangela now everything should be ok, can you please check?

**Comment by innovativeangela** [comment]
@fabio-bs This looks really good. Can the tooltip text be changed to be more descriptive for users? I will add text to explain Basic/Champion/Hero on the landing page as well. 
Basic: Tooltip text: "Allows reuse"
Champion: Tooltip text: "Can be remixed"
Hero: Tooltip text: "Editable source files available"

**Comment by fabio-bs** [comment]
I added the descriptions you provided below the Adaptability name

**Comment by innovativeangela** [comment]
@fabio-bs I noticed that tooltips only appear on the toolkit detail pages. Can they also be added to the badges on the filter pages? Also, could you change the Adaptability name in the toolkit text to "HERO:" "CHAMPION:" and "BASIC:" ? (all caps and with a : at the end)

**Comment by fabio-bs** [comment]
I modified the titles as you requested (all caps and with a : at the end). 
On the live site to me the tooltips work properly also on the search page, can you check again? is it possible that you were looking at the staging site where the descriptions were not yet present?
