### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: add content to Open Government guide page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#18]
Add the following text (matching styling on the site - "pillars of open government" is a header) to the Open Government guide page between "Open Government Recommendation includes 10 provisions grouped into enablers, implementation support, and  moving towards open state." and the 3 buttons you created. 

********

Pillars  of open government 
•	Open government enablers
These elements are important preconditions  for  creating Open Government strategies and initiatives, including policy and legal frameworks; human, financial, and technical resources; political commitment and open government literacy

•	Open government implementation
Elements to support implementation include coordination mechanisms across government; monitoring and evaluation mechanisms; communication and  stakeholder engagement. Implementation also includes use of evidence such as open data and digital tools to support participation;

•	Open state implies working across level and branches of government to design, coordinate and implement an Open Government agenda.

**Comment by fabio-bs** [comment]
Hello Angela, I added the text as requested

**Comment by innovativeangela** [comment]
@fabio-bs I received updated instructions from the open gov team. Instead of including this content on the open government guide page, can you please delete/move these to the top of each of the related sub-pages pertaining to the 3 pillars?

**Comment by fabio-bs** [comment]
@innovativeangela I moved the texts in the three related subpages. Do I also have to remove the "Pillars of open government" header?

**Comment by innovativeangela** [comment]
@fabio-bs Thanks. The Pillars of open government header should remain but be moved above "Open Government Recommendation includes 10 provisions grouped into enablers, implementation support, and  moving towards open state." Once the site is live, I can make all these annoying little text changes :)

**Comment by fabio-bs** [comment]
No problem :) I moved the text as you indicated.

**Comment by innovativeangela** [comment]
The Open Gov team would like the "How do I..." options to appear as follows:

•	Design an open government strategy or initiative?
•	Bring new perspectives and stakeholders into the policy process?
•	Communicate open government initiatives?
•	Develop monitoring, evaluation and learning mechanisms for open government strategies and initiatives?

**Comment by innovativeangela** [comment]
Also, the option at the top left of the page currently reads: 
The OPSI community has experts in this area
[Connect with them](https://oecd-opsi.org/opsi-network/)

Please change on this page (and all other guide pages) to:
Contact other experts in this area
[Log in to connect](https://oecd-opsi.org/members/?members_search=Open+Government)

Please also make these changes to all of the other guide pages based on topic. For instance, the "Log in to connect" option on the Systems Change page will link to the list of members with "Systems Change" tagged in their profile.

**Comment by fabio-bs** [comment]
I made the changes to the "How do I" options as requested by the Open Gov team

**Comment by fabio-bs** [comment]
On the staging site, I have also modified the link to search for experts and differentiating it based on whether a user is logged in or not
