### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: Add content to Design an open government strategy guide page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#19]
Replace lorem ipsum text on [Design an open government strategy or initiative](https://staging.oecd-opsi.org/guide/open-government/design-an-open-government-strategy-orinitiative/) guide page with the following

*********

Open Government initiatives should not be planned or put into practice at random. The implementation of an open government agenda requires strategic thinking and practical coordination across levels and branches of government.  When a holistic approach is not adopted, governments can confuse open government policies with isolated activities which are not supporting with each other and that might fail to deliver the desired outcomes.
The OECD has recommended countries to adopt a whole-of-government National Open Government Strategy, which should count with the highest possible level of political support. This kind of strategy would have clear goals, key initiatives to achieve these goals, resources to back up its implementation, and methods to evaluate what progress has been achieved.
In this section, you will find a selection of toolkits that give guidance to design a strategy and establish coordination practices with institutions across government levels.
Although few countries or local governments have developed  open government strategies, in some cases the open government agenda  is referred to strategic documents related to digital government, open data or public administration reform.

**Comment by fabio-bs** [comment]
Hello Angela, I replaced the text as requested
