### ISSUE TITLE
"I have used this" 

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#2]
This would appear in the Review section of individual toolkit detail pages. Similar to the Save feature, the "I have used this" button would be available to both logged in and not logged in users. Not logged in users would be able to click the button and will be prompted with an option to "Log in to see others who have also used this" or "See others who have also used this" if they are already logged in. Their click would also be associated with their user profile. Both "see others" prompts would only appear on toolkit detail pages for which at least one other logged in user has clicked the button. 
The use data (in addition to Save data) would inform relevance sorting on the toolkit filter page.
For logged in users, clicking "I have used this" also adds an experience tag to their user profile based on the Discipline(s) or Practice(s) associated with the toolkit.

**Comment by fabio-bs** [comment]
currently the button "I have used this" that we have created has a dual function: clicking it for the first time sets the toolkit as used, while a second click removes the information (it can be useful in case a user makes a click by mistake) . Our proposal is therefore to insert an independent button "Show others who have used this toolkit" that shows the list of users (see attached screenshots).
Logged in user:
![used-toolkit-mockup](https://user-images.githubusercontent.com/9032846/48343444-b27d0c80-e672-11e8-8342-877838920e93.jpg)

User not logged in:
![non-logged-in_used-toolkit-mockup](https://user-images.githubusercontent.com/9032846/48343445-b27d0c80-e672-11e8-8cb4-066d98e33702.jpg)

**Comment by fabio-bs** [comment]
I added the button as described in the previous message which, if clicked, displays a popup window listing the users who used the toolkit as shown in the following image:
![saved-popup](https://user-images.githubusercontent.com/9032846/48436894-340e9080-e780-11e8-9935-194cb0110dc3.JPG)

I have also created some screenshots that show the behavior of the page in various situations.
Saved toolkit - Logged in user:
![saved-loggedin](https://user-images.githubusercontent.com/9032846/48436917-47216080-e780-11e8-9d60-0143043289c4.JPG)
Saved toolkit - Not logged in user:
![saved-nonloggedin](https://user-images.githubusercontent.com/9032846/48436918-47216080-e780-11e8-8ef1-db9e1932e0ca.JPG)

Not saved toolkit - Logged in user:
![nonsaved-loggedin](https://user-images.githubusercontent.com/9032846/48436948-60c2a800-e780-11e8-94ce-da96da6974d0.JPG)
Not saved toolkit - Not Logged in user:
![nonsaved-nonloggedin](https://user-images.githubusercontent.com/9032846/48436950-60c2a800-e780-11e8-96c4-ec28554cddda.JPG)

**Comment by innovativeangela** [comment]
@fabio-bs these scenarios make a lot of sense. I really like the popup list of other users who have used the toolkits. For the scenario "not saved toolkit - not logged in user" can you remove the text "this toolkit has not yet been used" unless the toolkit has been used by at least one person, in which case "log in to see others who have used this" will appear? I do not want to give the impression that the toolkit has never been used by anyone--toolkit publishers will be unhappy about this. Also remove this text from the scenario "Not saved toolkit - Logged in user" 
Also, for the scenario "not saved toolkit - not logged in user" could you please add an option in the same area "log in to save toolkit or connect with other toolkit users" which prompts login?

**Comment by fabio-bs** [comment]
@innovativeangela I made the change, can you please check if I have correctly interpreted your request?

**Comment by innovativeangela** [comment]
@fabio-bs Yes, this looks great
