### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: Add content to Bring new perspectives guide page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#20]
Replace lorem ipsum text on [Bring new perspectives...](https://staging.oecd-opsi.org/guide/open-government/bring-new-perspectives-and-stakeholders-into-policy-process/) guide page with the following text

*******

The process of designing, implementing and evaluating open government strategies and initiatives is integrated with intense communication and engaging a diverse scale of  stakeholders. Youth, women, geographically distant communities, persons with special needs should have equal voice in  co-creating policies and influencing public decisions. This section describes principles and methods to engage with stakeholders, ways to use evidence and digital tools to enrich the  discussion and aim for optimal solutions in policy or service design.

**Comment by fabio-bs** [comment]
I replaced the text as requested
