### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: Add content to Communicate guide page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#21]
Replace lorem ipsum text on [Communicate...](https://staging.oecd-opsi.org/guide/open-government/communicate-open-government-work/) guide page with the following text

**********

Open government promotes the values of transparency, integrity, accountability and participation. As such, it is important that governments communicate clearly what they are doing to deliver open government programmes, why they are doing it, and what benefits they offer citizens and other stakeholders. This section presents guidance on what  are the elements of a dedicated communications strategy related to open government initiatives and the institutional set-up to ensure its implementation.

**Comment by fabio-bs** [comment]
I replaced the text as requested
