### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: Add content to Monitor guide page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#22]
Replace lorem ipsum text on [Monitor...](https://staging.oecd-opsi.org/guide/open-government/monitor-and-evaluate-open-government-work/) guide page with the following text

********

Monitoring and evaluation (M&E) is a core element of the Open Government Strategy and ensures that the strategy and initiatives are achieving the intended goals and objectives. Evaluation helps to identify challenges affecting the implementation of public policies and provide responses to overcome them based on lessons learned from previous successes and failures. Both are equally relevant to provide legitimacy for the use of public funds and resources.

**Comment by fabio-bs** [comment]
I replaced the text as requested
