### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: Banner on 7 open gov sub-pages

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#23]
Please add banner logos to the top of the 7 open government sub-pages (but not the main open government guide page) as shown in the attached mockup. 
[OpenGov Toolkit Navigator Logo placement mockup.pptx](https://github.com/oecd-opsi/meta-toolkit/files/2549287/OpenGov.Toolkit.Navigator.Logo.placement.mockup.pptx)
![ogp_logo_-_print_layers](https://user-images.githubusercontent.com/22620143/48007207-6c2a2980-e117-11e8-932d-e1d88738a0f2.png)
![cover image for print use](https://user-images.githubusercontent.com/22620143/48007208-6c2a2980-e117-11e8-997a-3b8e1fff6e25.jpg)
![oecd_text_20cm](https://user-images.githubusercontent.com/22620143/48007304-9c71c800-e117-11e8-8c4a-b26c1f19f920.jpg)

**Comment by fabio-bs** [comment]
Should the final result be like the one shown in the attached image I created? or do the logos have to be placed around the page title (for example "Design an open government strategy or initiative")?
![opengov-header](https://user-images.githubusercontent.com/9032846/48009995-fe80fc00-e11c-11e8-85dd-d1bc402f09f4.jpg)

**Comment by innovativeangela** [comment]
Yes, this is great.

**Comment by fabio-bs** [comment]
@innovativeangela I have another question about this: in the mobile version of the site, the banner keeps the same format as shown in the attached file? 
![opengov-header-mobile](https://user-images.githubusercontent.com/9032846/48015725-18750b80-e12a-11e8-87e6-f28523c37a26.jpg)

**Comment by innovativeangela** [comment]
@fabio-bs Yes, it is not ideal but it is ok for now

**Comment by fabio-bs** [comment]
@innovativeangela I inserted the banner (as an image to fit the page width) in the 7 open government sub-pages

**Comment by innovativeangela** [comment]
@fabio-bs the open gov team would like the text "OECD" removed from the "OECD Open Government" banner on all 7 pages

**Comment by fabio-bs** [comment]
I made the change as requested
