### ISSUE TITLE
Feedback Open Gov Toolkit Navigator: "Go to case studies"

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#24]
On each of the 7 open gov sub-pages, the "Go to case studies" link should link to the [Open Government Case Studies view](https://staging.oecd-opsi.org/case_type/open-government/) instead of the current OPSI case studies view

**Comment by fabio-bs** [comment]
@innovativeangela I updated the links of the 7 open gov sub-pages
