### ISSUE TITLE
Feedback on Open Gov Toolkit Navigator: Placement of "View all toolkits for x"

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#25]
Currently, on each of the guide pages ([example](https://oecd-opsi.org/guide/open-government/)) the placement of the link "View all toolkits for "[Discipline or Practice]" appears below the list of toolkits on the right side of each the page. 

Can this link be moved between "Open Government toolkits" and the first toolkit listing? 
 I understand this will change the format of all the guide pages, but that is desirable. 

[All Toolkits.pptx](https://github.com/oecd-opsi/meta-toolkit/files/2553708/All.Toolkits.pptx)

**Comment by fabio-bs** [comment]
I moved the link as required, the result is visible on the [staging site](https://staging.oecd-opsi.org/guide/open-government/)

**Comment by innovativeangela** [comment]
@fabio-bs can you please push these changes to the live site?

**Comment by fabio-bs** [comment]
Yes, I pushed the change even on the live site.
