### ISSUE TITLE
Feedback on Open Gov Toolkit Navigator: Toolkit tagging

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#26]
Open gov team would like [this toolkit](https://oecd-opsi.org/toolkits/ogps-participation-and-co-creation-toolkit-from-usual-suspects-to-business-as-usual/) to appear in the list of options when users click "Design an open government strategy or initiative?" on the [open government guide page](https://oecd-opsi.org/guide/open-government/).

**Comment by fabio-bs** [comment]
I added the "Design an open government strategy or initiative?" tag to the toolkit you specified on the live site.
