### ISSUE TITLE
Contact experts in this area

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#28]
@fabio-bs On the guide pages, for instance [this one](https://oecd-opsi.org/guide/systems-change/), not logged in users see "Log in to connect to experts in this area" and upon login, they are taken to their own profile instead of the list of users related to systems change. The user has to go back and click on "Find experts in this area" in order to find the list of user profiles. Can this be changed so that users see the list of systems change users just after logging in?

**Comment by fabio-bs** [comment]
It should now work properly
