### ISSUE TITLE
Migration: "Go to case studies" on detail pages

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#29]
@fabio-bs 
[Example page](https://oecd-opsi.org/toolkits/assessing-innovation-potential-for-social-impact/): in the box "See cases of others doing this in government" the link "Go to case studies" directs to [this page](https://oecd-opsi.org/our-work/case-studies/), which is blank. On all toolkit detail pages, can this be fixed? It should link to the [OPSI case study platform](https://oecd-opsi.org/case_type/opsi/) with the relevant Discipline or Practice filtered (in this case, "Systems Change"). I think this issue was created due to the recent changes to the case study platform.

**Comment by fabio-bs** [comment]
I changed the link as requested
