### ISSUE TITLE
Migration: "Find experts..." on detail pages

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#30]
@fabio-bs 
On detail pages (example), in the "Find experts and advisers who can assist me with this" box, the link "Go to advice" directs to [this page](https://oecd-opsi.org/about-observatory-of-public-sector-innovation/about-our-in-country-contacts/), which is blank. This page used to have content. Can it be recovered? 
In any case, this should work similarly to how it works on guide pages: logged in users will have the option "Log in to connect to experts in this area" and logged in users will see "Go to advice" which directs to a filtered list of users based on the relevant Discipline (in this case, Systems Change).

**Comment by innovativeangela** [comment]
@fabio-bs Actually, the content is there, just way down at the bottom of the page and aligned to the left. This seems to be an issue for several Pages.

**Comment by fabio-bs** [comment]
Now this page seems to appear correctly, can I consider this issue closed?

**Comment by fabio-bs** [comment]
As a result of our Skype conversation, I modified the link to point to the member search page similar to how it works on guide pages. The research is based on the first relevant Discipline.
