### ISSUE TITLE
wp-admin bar appears for new users

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#31]
When a new user logged in, he was able to see the wp-admin toolbar at the top of his page. He was able to view the backend and look through toolkits, cases, etc. New users should not be able to access the backend. 
@marcochiesi or @fabio-bs can you please look into this?

**Comment by fabio-bs** [comment]
For "new user" do you mean subscribers with the "Pending" role? Now I have hidden the toolbar for users with this role

**Comment by innovativeangela** [comment]
Yes, I meant pending users. Thank you.

**Comment by jlberryhill** [comment]
Thanks, @fabio-bs. Could you please make it so the toolbar only appears for full Administrators? Thanks!

**Comment by fabio-bs** [comment]
@jlberryhill for full administrators, do you mean only users with the "Administrator" role or other roles (for example, editors like @innovativeangela)? Below is a list with all the roles on the site, can you tell me if among these there are other roles that must be able to see the toolbar?

 Academia and Research 
 Administrator 
 Author 
 Contributor 
 Editor (e.g. Angela Hanson)
 NGO and Civil Society 
 National Contact Points 
 Open Gov administrators 
 Pending 
 Private Sector 
 Public Sector 
 SEO Editor 
 SEO Manager 
 Subscriber 
 No role

**Comment by jlberryhill** [comment]
Hi @fabio-bs -- only Administrator.

**Comment by jlberryhill** [comment]
@fabio-bs -- And to be clear, only users that are Administrator, Author, Contributor, Editor, Open Gov Administrators should have any access to wp-admin at all.

**Comment by fabio-bs** [comment]
@jlberryhill I made the changes as requested

**Comment by jlberryhill** [comment]
Thanks, @fabio-bs -- The admin bar is now gone for Administrators. Is it possible to add it back for just this permissions group?

**Comment by fabio-bs** [comment]
@jlberryhill The problem was due to a conflict in a configuration of the "User Role Editor" plugin that appeared to users like yours with multiple assigned roles. It should now work properly

**Comment by jlberryhill** [comment]
@fabio-bs Hi Fabio - still seems to be some issues here. Only Administrators seem to be able to access the Dashboard (/wp-admin/ page).  The users below should be able to access the Dashboard by going to the wp-admin page. The admin ribbon at the top should only appear for Administrators. 

Administrator
Author
Contributor
Editor 
Open Gov Administrators

**Comment by fabio-bs** [comment]
Hi @jlberryhill I did some tests with users belonging to the various roles on the site but I did not find any problems. Can you please tell me if there are specific users who are experiencing the problem?
