### ISSUE TITLE
Improved search functionality

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#6]
On both [landing page](https://oecd-opsi.org/toolkit-navigator/) and [filter page](https://oecd-opsi.org/search-toolkits/). This would be improved based on usage data as well as autocomplete feature on search box.

**Comment by marcochiesi** [comment]
This issue seems a combination of the issues #4 (autocomplete) and #3 (sort).
Is it necessary to have a distinct issue for this?
