### ISSUE TITLE
Collections on landing page

### ISSUE THREAD

**Issue by innovativeangela** [oecd-opsi/meta-toolkit#7]
On Toolkit Navigator landing page, toolkit collections would be featured, such as “Starter kit” or “Game-based toolkits,” which can be changed quickly by administrators to feature certain content. These would link to a filtered view of toolkits based on existing fields OR a manual curation made by administrators.  
Mockup
![image](https://user-images.githubusercontent.com/22620143/46860711-4c059400-ce11-11e8-9931-1fcb0c4a3bdd.png)

**Comment by fabio-bs** [comment]
@innovativeangela I added the "Featured" taxonomy to the toolkits with the three tags shown in the mockup. In the [Navigator Toolkit](https://staging.oecd-opsi.org/toolkit-navigator/) I then displayed the three links that lead to the filtered view. Can you please provide me with the descriptions to show under these links?

**Comment by innovativeangela** [comment]
@fabio-bs Will this be easy to change on the admin backend? What I am interested in is a filter that works either as a combination of taxonomy items (for instance: adaptability:hero AND discipline:design) or a custom curated selection. As it stands, the admin will have to tag each of the hundreds of toolkits with the featured taxonomy tag, which could be cumbersome depending on how this is handled on the backend. Will the backend allow for the application of tags based on a query (for instance, tag all adaptability:hero OR champion toolkits with "adaptable" in the featured taxonomy)? If not, then it might be better if the collections on the front page instead link to filtered views based on existing taxonomy items.

**Comment by fabio-bs** [comment]
@innovativeangela based on what you said, I think the "Featured" taxonomy is not ideal. Our proposal is therefore to create a panel (always named "Featured") in which, for each button, you can specify title, description and search URL. The search URL can be obtained by copying it from the pre-filtered search page: for example https://staging.oecd-opsi.org/search-toolkits/?_sft_discipline-or-practice=design&_sft_adaptability=hero
What do you think about this?

**Comment by fabio-bs** [comment]
I implemented what described in the previous message, the buttons can be easily managed from the following [page](https://staging.oecd-opsi.org/wp-admin/edit.php?post_type=toolkit&page=acf-options-featured) where I added three example buttons that link to the filtered view using existing taxonomy items.
